# Site settings
title: vsCommandEvent
subtitle: Flexible actions for all  ...
email: entry.reg@gmail.com
baseurl: ""
url: "http://vsce.r-eg.net" # base hostname
domain: "vsce.r-eg.net"

# root path to doc structure
docp: "/doc"
#permalink: pretty

collections:
    doc: # main documentation
        output: true


# Build settings
markdown: kramdown

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "space_after_headers", "footnotes", "prettify"]

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    auto_ids: true # generate ID for headings
    input: GFM # +GitHub Flavored Markdown
  
#highlighter: pygments
highlighter: rouge

# suitable langs with rouge as the SBE-Scripts
sbelang: clojure
sbelang1: java
sbelang2: tcl
sbelang3: ocaml

# suitable langs with rouge as the MSBuild properties and Property Functions
msblang: bash


#######################################
# Latest binaries
##############

# Downloads
         # Specifies variables with prefix:
            # 'lnkCur_' - Actual or recommended version. /Format: [ "short name", "full name", "link" ]
            # 'lnkList_' - List of all previous versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkOld_' - List of all deprecated versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkAll_' - Link to browsing all available versions. /Format: [ "name", "link" ]


## VSPackage

lnkCur_VSPackage:   [ "v1.2.0", "vsCommandEvent&#95;v1.2.0.11076&#95;a7bae2f&#95;net40.vsix", "https://visualstudiogallery.msdn.microsoft.com/ad9f19b2-04c0-46fe-9637-9a52ce4ca661/file/184640/6/" ]
lnkList_VSPackage:  [
                        [ "v1.2.0_net40", "vsCommandEvent&#95;v1.2.0.11076&#95;a7bae2f&#95;net40.vsix", "https://sourceforge.net/projects/vssbe/files/vsCommandEvent/v1.x/net40/vsCommandEvent_v1.2.0.11076_a7bae2f_net40.vsix/download" ],
                        [ "v1.2.0_net45", "vsCommandEvent&#95;v1.2.0.11077&#95;a7bae2f&#95;net45.vsix", "https://sourceforge.net/projects/vssbe/files/vsCommandEvent/v1.x/net45/vsCommandEvent_v1.2.0.11077_a7bae2f_net45.vsix/download" ],
                        [ "v1.1.0", "vsCommandEvent&#95;v1.1.0.672&#95;[9c1a9f7][net45].vsix", "https://sourceforge.net/projects/vssbe/files/vsCommandEvent/v1.x/vsCommandEvent_v1.1.0.672_%5B9c1a9f7%5D%5Bnet45%5D.vsix/download" ]
                    ]
lnkOld_VSPackage:   [
                        [ "v1.0.0", "vsCommandEvent&#95;v1.0.0.3751&#95;[7a415e0][net45].vsix", "http://sourceforge.net/projects/vssbe/files/vsCommandEvent/v1.x/vsCommandEvent_v1.0.0.3751_%5B7a415e0%5D%5Bnet45%5D.vsix/download" ]
                    ]
lnkAll_VSPackage:   [ "/v1.x/", "https://sourceforge.net/projects/vssbe/files/vsCommandEvent/v1.x/" ]

## used vsSBE

verUsedVSSBE: "v0.12.9"

#######################################
# Sources
##############

# Web

lnkVSGallery: "http://visualstudiogallery.msdn.microsoft.com/ad9f19b2-04c0-46fe-9637-9a52ce4ca661/"

# Dev

lnkBackupLib: [ "/dev/lib/", "http://sourceforge.net/projects/vssbe/files/dev/lib/"]
lnkBackupSrc: [ "/vsCommandEvent/dev/src/", "https://sourceforge.net/projects/vssbe/files/vsCommandEvent/dev/src/" ]


# other

changelog: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/changelog.txt"
changelogVSSBE: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/changelog.txt"

readme: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/README.md"
license: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/LICENSE"

versionVsix: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/.version"

issueNew: "https://github.com/3F/vsCommandEvent/issues/new"
repoMain: "https://github.com/3F/vsCommandEvent"
repoMainFork: "https://github.com/3F/vsCommandEvent/fork"
repoMainStar: "https://github.com/3F/vsCommandEvent/star"


#######################################
# Services
##############

editPagePath: "https://github.com/3F/web.vsCE/edit/gh-pages/"
ghPagePrefix: "https://github.com/3F/web.vsCE"