# Site settings
title: vsCommandEvent
subtitle: Flexible actions for all  ...
email: entry.reg@gmail.com
baseurl: ""
url: "http://vsce.r-eg.net" # base hostname

# root path to doc structure
docp: "/doc"
#permalink: pretty

collections:
    doc: # main documentation
        output: true


# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "space_after_headers", "footnotes", "prettify"]

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    auto_ids: true # generate ID for headings
    input: GFM # +GitHub Flavored Markdown
  
highlighter: pygments


#######################################
# Latest binaries
##############

# Downloads
         # Specifies variables with prefix:
            # 'lnkCur_' - Actual or recommended version. /Format: [ "short name", "full name", "link" ]
            # 'lnkList_' - List of all previous versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkOld_' - List of all deprecated versions. /Format: [ [ "version or short name", "full name", "link" ], ... ]
            # 'lnkAll_' - Link to browsing all available versions. /Format: [ "name", "link" ]


## VSPackage

lnkCur_VSPackage:   [ "v1.0.0", "vsCommandEvent_v1.0.0.3751_[7a415e0][net45].vsix", "https://visualstudiogallery.msdn.microsoft.com/ad9f19b2-04c0-46fe-9637-9a52ce4ca661/file/184640/" ]
lnkList_VSPackage:  [
                        [ "v1.0.0", "vsCommandEvent_v1.0.0.3751_[7a415e0][net45].vsix", "http://sourceforge.net/projects/vssbe/files/vsCommandEvent/v1.x/vsCommandEvent_v1.0.0.3751_%5B7a415e0%5D%5Bnet45%5D.vsix/download" ]
                    ]
lnkOld_VSPackage:   []
lnkAll_VSPackage:   [ "/v1.x/", "https://sourceforge.net/projects/vssbe/files/vsCommandEvent/v1.x/" ]


#######################################
# Sources
##############

# Web

lnkVSGallery: "http://visualstudiogallery.msdn.microsoft.com/ad9f19b2-04c0-46fe-9637-9a52ce4ca661/"

# Dev

lnkBackupLib: [ "/dev/lib/", "http://sourceforge.net/projects/vssbe/files/dev/lib/"]
lnkBackupSrc: [ "/dev/sources/", "https://sourceforge.net/projects/vssbe/files/dev/sources/" ]


# other

changelog: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/changelog.txt"
changelogVSSBE: "https://raw.githubusercontent.com/3F/vsSolutionBuildEvent/master/changelog.txt"

readme: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/README.md"
license: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/LICENSE"

versionVsix: "https://raw.githubusercontent.com/3F/vsCommandEvent/master/.version"
